{% set name = "snap-cpp" %}
{% set version = "4.1" %}
{% set sha256 = "c756e0b4e6ed9681f1dc3d7405326208f6e3eb8f6b7a0ae547c4238a8c5c9f0e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: Snap-{{ version }}.zip
  url: http://snap.stanford.edu/releases/Snap-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 1000

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config

test:
  source_files:
    - examples
  commands:
    - cd examples/graphgen && ./graphgen -g:w -n:1000 -k:4 -p:0.1 -o:smallworld.txt
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]


about:
  home: http://snap.stanford.edu/snap/
  license: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/License.txt'
  summary: 'General purpose, high performance system for analysis and manipulation of large networks.'
  description: |
    Stanford Network Analysis Platform (SNAP) is a general purpose, 
    high performance system for analysis and manipulation of large 
    networks. Graphs consists of nodes and directed/undirected/multiple 
    edges between the graph nodes. Networks are graphs with data on 
    nodes and/or edges of the network.
  doc_url: http://snap.stanford.edu/snap/doc.html
  dev_url: https://github.com/snap-stanford/snap

extra:
  recipe-maintainers:
    - CurtLH
