{% set name = "snap-cpp" %}
{% set version = "6.0" %}
{% set sha256 = "3322960a9376ae33349bddb62bb04b07891d23b4b461e52c1ed562d79b73f55a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: Snap-{{ version }}.zip
  url: http://snap.stanford.edu/releases/Snap-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config

test:
  source_files:
    - examples
  commands:
    - cd examples/graphgen && ./graphgen -g:w -n:1000 -k:4 -p:0.1 -o:smallworld.txt


about:
  home: http://snap.stanford.edu/snap/
  license: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/License.txt
  summary: General purpose, high performance system for analysis and manipulation of large networks.
  description: |
    Stanford Network Analysis Platform (SNAP) is a general purpose, 
    high performance system for analysis and manipulation of large 
    networks. Graphs consists of nodes and directed/undirected/multiple 
    edges between the graph nodes. Networks are graphs with data on 
    nodes and/or edges of the network.
  doc_url: http://snap.stanford.edu/snap/doc.html
  dev_url: https://github.com/snap-stanford/snap

extra:
  recipe-maintainers:
    - CurtLH
