travis:
  secure:
    BINSTAR_TOKEN: htWN/mTeaHESGaOQdy3seivD4PUkLxMBjgIrXJqCj4uNBb7YeEOheYU+Tr4CutanEA8icvUGd6OAeTHqlmTh5uuKNUe9toIstctcVhQh3+oIDzkBqvzg9LCqbeukF2895c0uUDE91sP7JKq6ruKflxBDg3BtZ4P6NDaxam8DDQyN7/n70TYfmauDlF/TgvVYfsYEfv33V9/toQ1WKjjCL23V1nh5wNMQD4FagLASbzoMF0hr2Cv9/rL8X/s2YuTAuw/SWrwAWr6//2Z43LD71t31y+Unp5xN3lMEZTznLl003aT61NZuxNkuznrRP1anugLKcaGxVNHF1MFRX1bLxenrKGifhNtLylR3XPQEbBa+RZ648yUyEXAJsiuuGoX+6/dp7ZODfZRNQMO3jE9irlGyYmsPnLXsC0MD5PKoJp7LH5K4Dob9wMOM8Rx8DoxkJ9Z7M0En3wJnKxp4RQrn1HUrca9stPGwW9V5c9322SB+L/LroLKgfcVLVXWIl1UivLHw2XxTd8B0tJVGVif2bMyxN84xVc61f8ZrdPVMxShEjYRsOhGAIkrcGA2epmI5ATzhFjKJlS3XSDChjUIkh9MM8diZGps7MrmoQFPKunp03y/P+mo9WsVx4zcqRhcUVIkdoQB+SjAnUQ9XEsYxUQW5KuisoBvmPgxng89+9Ds=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
